-- WVP-GB28181 Go版本数据库初始化脚本
-- 创建设备表
CREATE TABLE IF NOT EXISTS wvp_device (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255),
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    firmware VARCHAR(255),
    transport VARCHAR(50),
    stream_mode VARCHAR(50),
    on_line BOOLEAN DEFAULT FALSE,
    ip VARCHAR(50),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    port INTEGER,
    expires INTEGER,
    subscribe_cycle_for_catalog INTEGER DEFAULT 0,
    subscribe_cycle_for_mobile_position INTEGER DEFAULT 0,
    mobile_position_submission_interval INTEGER DEFAULT 5,
    subscribe_cycle_for_alarm INTEGER DEFAULT 0,
    host_address VARCHAR(50),
    charset VARCHAR(50),
    ssrc_check BOOLEAN DEFAULT FALSE,
    geo_coord_sys VARCHAR(50),
    media_server_id VARCHAR(50) DEFAULT 'auto',
    custom_name VARCHAR(255),
    sdp_ip VARCHAR(50),
    local_ip VARCHAR(50),
    password VARCHAR(255),
    as_message_channel BOOLEAN DEFAULT FALSE,
    heart_beat_interval INTEGER,
    heart_beat_count INTEGER,
    position_capability INTEGER,
    broadcast_push_after_ack BOOLEAN DEFAULT FALSE,
    server_id VARCHAR(50)
);

-- 创建通道表
CREATE TABLE IF NOT EXISTS wvp_device_channel (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50),
    name VARCHAR(255),
    manufacturer VARCHAR(50),
    model VARCHAR(50),
    owner VARCHAR(50),
    civil_code VARCHAR(50),
    block VARCHAR(50),
    address VARCHAR(50),
    parental INTEGER,
    parent_id VARCHAR(50),
    safety_way INTEGER,
    register_way INTEGER,
    cert_num VARCHAR(50),
    certifiable INTEGER,
    err_code INTEGER,
    end_time VARCHAR(50),
    secrecy INTEGER,
    ip_address VARCHAR(50),
    port INTEGER,
    password VARCHAR(255),
    status VARCHAR(50),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    ptz_type INTEGER,
    position_type INTEGER,
    room_type INTEGER,
    use_type INTEGER,
    supply_light_type INTEGER,
    direction_type INTEGER,
    resolution VARCHAR(255),
    business_group_id VARCHAR(255),
    download_speed VARCHAR(255),
    svc_space_support_mod INTEGER,
    svc_time_support_mode INTEGER,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sub_count INTEGER,
    stream_id VARCHAR(255),
    has_audio BOOLEAN DEFAULT FALSE,
    gps_time VARCHAR(50),
    stream_identification VARCHAR(50),
    channel_type INTEGER DEFAULT 0,
    map_level INTEGER DEFAULT 0,
    gb_device_id VARCHAR(50),
    gb_name VARCHAR(255),
    gb_manufacturer VARCHAR(255),
    gb_model VARCHAR(50),
    gb_owner VARCHAR(50),
    gb_civil_code VARCHAR(50),
    gb_block VARCHAR(50),
    gb_address VARCHAR(50),
    gb_parental INTEGER,
    gb_parent_id VARCHAR(50),
    gb_safety_way INTEGER,
    gb_register_way INTEGER,
    gb_cert_num VARCHAR(50),
    gb_certifiable INTEGER,
    gb_err_code INTEGER,
    gb_end_time VARCHAR(50),
    gb_secrecy INTEGER,
    gb_ip_address VARCHAR(50),
    gb_port INTEGER,
    gb_password VARCHAR(50),
    gb_status VARCHAR(50),
    gb_longitude DOUBLE PRECISION,
    gb_latitude DOUBLE PRECISION,
    gb_business_group_id VARCHAR(50),
    gb_ptz_type INTEGER,
    gb_position_type INTEGER,
    gb_room_type INTEGER,
    gb_use_type INTEGER,
    gb_supply_light_type INTEGER,
    gb_direction_type INTEGER,
    gb_resolution VARCHAR(255),
    gb_download_speed VARCHAR(255),
    gb_svc_space_support_mod INTEGER,
    gb_svc_time_support_mode INTEGER,
    record_plan_id INTEGER,
    data_type INTEGER NOT NULL,
    data_device_id INTEGER NOT NULL,
    gps_speed DOUBLE PRECISION,
    gps_altitude DOUBLE PRECISION,
    gps_direction DOUBLE PRECISION,
    enable_broadcast INTEGER DEFAULT 0,
    CONSTRAINT uk_wvp_unique_channel UNIQUE (gb_device_id),
    CONSTRAINT uk_device_channel_source UNIQUE (data_device_id, device_id)
);

-- 创建媒体服务器表
CREATE TABLE IF NOT EXISTS wvp_media_server (
    id VARCHAR(255) PRIMARY KEY,
    ip VARCHAR(50),
    hook_ip VARCHAR(50),
    sdp_ip VARCHAR(50),
    stream_ip VARCHAR(50),
    http_port INTEGER,
    http_ssl_port INTEGER,
    rtmp_port INTEGER,
    rtmp_ssl_port INTEGER,
    rtp_proxy_port INTEGER,
    rtsp_port INTEGER,
    rtsp_ssl_port INTEGER,
    flv_port INTEGER,
    flv_ssl_port INTEGER,
    mp4_port INTEGER,
    mp4_ssl_port INTEGER,
    ws_flv_port INTEGER,
    ws_flv_ssl_port INTEGER,
    auto_config BOOLEAN DEFAULT FALSE,
    secret VARCHAR(50),
    type VARCHAR(50) DEFAULT 'zlm',
    rtp_enable BOOLEAN DEFAULT FALSE,
    rtp_port_range VARCHAR(50),
    send_rtp_port_range VARCHAR(50),
    record_assist_port INTEGER,
    default_server BOOLEAN DEFAULT FALSE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建平台表
CREATE TABLE IF NOT EXISTS wvp_platform (
    id SERIAL PRIMARY KEY,
    enable BOOLEAN DEFAULT TRUE,
    domain VARCHAR(50) NOT NULL,
    name VARCHAR(255),
    registrar_port INTEGER,
    registrar_transport VARCHAR(50),
    registrar_ip VARCHAR(50),
    share_channel BOOLEAN DEFAULT TRUE,
    id_code VARCHAR(50),
    device_id VARCHAR(50),
    catalog_id VARCHAR(50),
    as_server_id VARCHAR(50),
    sip_ip VARCHAR(50),
    sip_port INTEGER,
    local_ip VARCHAR(50),
    send_stream_port INTEGER,
    administrative_division VARCHAR(50),
    catalog_way INTEGER DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_domain UNIQUE (domain)
);

-- 创建录像计划表
CREATE TABLE IF NOT EXISTS wvp_record_plan (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    week INTEGER,
    begin_time VARCHAR(50),
    end_time VARCHAR(50),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建录像文件表
CREATE TABLE IF NOT EXISTS wvp_record_file (
    id SERIAL PRIMARY KEY,
    app VARCHAR(255),
    stream VARCHAR(255),
    file_path VARCHAR(255),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    channel_id VARCHAR(50),
    device_id VARCHAR(50),
    server_id VARCHAR(50),
    file_size BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX idx_device_device_id ON wvp_device(device_id);
CREATE INDEX idx_device_online ON wvp_device(on_line);
CREATE INDEX idx_channel_device ON wvp_device_channel(device_id);
CREATE INDEX idx_channel_gb_device ON wvp_device_channel(gb_device_id);
CREATE INDEX idx_channel_status ON wvp_device_channel(status);
CREATE INDEX idx_record_channel ON wvp_record_file(channel_id);
CREATE INDEX idx_record_time ON wvp_record_file(start_time, end_time);